spring.application.name=food-app

jwt.secret=a20b736060462720c23baa2d590ee5b259384eb445a9b5f2ab197542332ab720
jwt.expiration=86400000

# ===================================================================
# Database Connection (PostgreSQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/food_app_db
spring.datasource.username=food_user
spring.datasource.password=user_test
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# JPA / Hibernate Configurations
# ===================================================================
# Options: update, validate, create, create-drop
spring.jpa.hibernate.ddl-auto=create

# Show SQL queries in the terminal during development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Open-In-View pattern setting (recommended false for clean service-layer transaction boundaries)
spring.jpa.open-in-view=false